version: '3.8'
services:
  web:
    build: .
    container_name: web
    ports:
      - "8080:8080"
    depends_on:
      - sk-db
    environment:
      - DB_NAME=db
      - DB_HOST=sk-db
      - DB_PORT=5432
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  web-1:
    build: .
    container_name: web-1
    ports:
      - "8081:8080"
    depends_on:
      - sk-db
    environment:
      - DB_NAME=db
      - DB_HOST=sk-db
      - DB_PORT=5432
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  web-2:
    build: .
    container_name: web-2
    ports:
      - "8082:8080"
    depends_on:
      - sk-db
    environment:
      - DB_NAME=db
      - DB_HOST=sk-db
      - DB_PORT=5432
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  sk-db:
    image: postgres:13.7-alpine
    container_name: sk-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
