DROP TABLE IF EXISTS sk_example_table;

CREATE TABLE sk_example_table
(
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    obj jsonb NOT NULL
);

INSERT INTO sk_example_table (obj) VALUES ('{"current":0}'::jsonb);